# Build project
FROM node:16 AS BUILD_IMAGE

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn --production

COPY . .

RUN yarn build

# Create minified image
FROM node:16-alpine

WORKDIR /app

COPY --from=BUILD_IMAGE /app/.nuxt ./.nuxt
COPY --from=BUILD_IMAGE /app/package*.json ./
COPY --from=BUILD_IMAGE /app/yarn.lock ./
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules
COPY --from=BUILD_IMAGE /app/static ./.nuxt

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
ENV BASE_URL=https://nikcio.com

EXPOSE 3000

CMD ["yarn", "dev"]
