version: '3'

services:
  personal-site_website-fe:
    container_name: personal-site_website-fe-v2
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
      - "24678:24678"
