version: '3'

services:
  personal-site_website-fe:
    container_name: personal-site_website-fe
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - "./assets:/app/nuxt/assets"
      - "./components:/app/nuxt/components"
      - "./pages:/app/nuxt/pages"
      - "./public:/app/nuxt/public"
      - "./store:/app/nuxt/store"
      - "./app.vue:/app/nuxt/app.vue"
      - "./nuxt.config.js:/app/nuxt/nuxt.config.js"
      - "./package.json:/app/package.json"