# Build project
FROM node:17

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn

WORKDIR /app/nuxt

COPY . .

WORKDIR /app

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000
EXPOSE 24678

CMD ["yarn", "run", "nuxi", "dev", "/app/nuxt"]