global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: INFO

entryPoints:
  defaulthttp:
    address: :5000

  defaultsecure:
    address: ":5100"

  dashboard:
    address: :8080
  
api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

accessLog:
  filePath: "/logs/access.log"
  format: json

log:
  filepath: "/logs/traefik.log"
  format: json
  level: ERROR