global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: INFO

entryPoints:
  defaulthttp:
    address: :80
    http:
      redirections:
        entryPoint:
          to: defaultsecure
          scheme: https

  defaultsecure:
    address: ":433"

  dashboard:
    address: :8080
  
api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

accessLog:
  filePath: "/logs/access.log"
  format: json

log:
  filepath: "/logs/traefik.log"
  format: json
  level: ERROR