version: '3'

services:
  uptime-kuma:
    container_name: Uptime-Kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=false"
      # Traefik enable
      - "traefik.enable=true"
      # Entrypoints
      - "traefik.http.routers.uptime-kuma.entrypoints=defaulthttp, defaultsecure"
      # Domains
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime.nikcio.com`)"
      - "traefik.http.routers.uptime-kuma.tls.domains[0].main=nikcio.com"
      - "traefik.http.routers.uptime-kuma.tls.domains[0].sans=*.nikcio.com"
      # TLS
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=defaultresolver"
      # Middlewares
      - "traefik.http.routers.uptime-kuma.middlewares=https"
      - "traefik.http.middlewares.https.redirectscheme.scheme=https"

    volumes:
      - "/home/nikcio/uptime/data:/app/data"

networks:
  default:
    external:
      name: traefik