global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: INFO

entryPoints:
  defaulthttp:
    address: :80

  defaultsecure:
    address: :443

certificatesResolvers:
  defaultresolver:
    acme:
      email: nikolajgive@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare

api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

accessLog:
  filePath: "/logs/access.log"
  format: json

log:
  filepath: "/logs/traefik.log"
  format: json
  level: ERROR